server:
  port: 8765

eureka:
  client:
    #eureka服务器通信的完全限定url
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    #主机名
    hostname: localhost
    #将IP注册到Eureka Server上
    prefer-ip-address: true
    #此实例注册到eureka服务端的唯一的实例ID
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
spring:
  application:
    name: service-provider